#!/bin/bash
# Per-user installer for the bhai-sunn STT launchd service.
# Customises start.sh and the plist for the current user, installs both,
# and bootstraps the launchd service.
#
# Run from the project root after the venv is set up and the model is cached.
# See deploy/README.md for the full prerequisites.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SERVICES_DIR="$HOME/services/bhai-sunn-stt"
USER_LABEL="bhai-sunn-stt"   # change to e.g. "com.adamya.bhai-sunn-stt" if you want a personal namespace
PLIST_LABEL="com.bhai-sunn.${USER_LABEL}"
PLIST_PATH="$HOME/Library/LaunchAgents/${PLIST_LABEL}.plist"

if [[ ! -d "$PROJECT_ROOT/.venv" ]]; then
  echo "ERROR: $PROJECT_ROOT/.venv not found. Run the venv + pip-install steps from deploy/README.md first." >&2
  exit 1
fi

if [[ ! -d "$HOME/.cache/huggingface/hub/models--ai4bharat--indic-conformer-600m-multilingual" ]]; then
  echo "ERROR: IndicConformer model not in HF cache. Pre-cache it before installing the service." >&2
  echo "       See deploy/README.md step 3." >&2
  exit 1
fi

echo "Installing bhai-sunn STT service for user $(whoami)"
echo "  project root:  $PROJECT_ROOT"
echo "  services dir:  $SERVICES_DIR"
echo "  plist:         $PLIST_PATH"

mkdir -p "$SERVICES_DIR"

# Generate start.sh with the actual project path
cat > "$SERVICES_DIR/start.sh" <<EOF
#!/bin/bash
# Auto-generated by deploy/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
set -euo pipefail
PROJECT="$PROJECT_ROOT"
cd "\$PROJECT"
exec "\$PROJECT/.venv/bin/uvicorn" \\
  prototype.stt_server:app \\
  --host 127.0.0.1 \\
  --port 8765 \\
  --log-level warning
EOF
chmod +x "$SERVICES_DIR/start.sh"

# Generate the plist with the actual paths and label
cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${PLIST_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${SERVICES_DIR}/start.sh</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${PROJECT_ROOT}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    <key>HF_HOME</key>
    <string>${HOME}/.cache/huggingface</string>
    <key>HF_HUB_OFFLINE</key>
    <string>1</string>
    <key>TRANSFORMERS_OFFLINE</key>
    <string>1</string>
  </dict>
  <key>StandardOutPath</key>
  <string>${SERVICES_DIR}/stdout.log</string>
  <key>StandardErrorPath</key>
  <string>${SERVICES_DIR}/stderr.log</string>
  <key>KeepAlive</key>
  <true/>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
EOF

# Bootstrap (or rebootstrap if already loaded)
launchctl bootout "gui/$(id -u)/${PLIST_LABEL}" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_PATH"

echo
echo "Service installed and started. Verify:"
echo "  curl -s http://127.0.0.1:8765/health"
echo
echo "Logs:"
echo "  tail -f $SERVICES_DIR/stderr.log"
echo
echo "Manage:"
echo "  launchctl kickstart -k gui/\$(id -u)/${PLIST_LABEL}    # restart"
echo "  launchctl bootout   gui/\$(id -u)/${PLIST_LABEL}        # stop"
